---
title: "Dependence models"
output: html_notebook
---

Here we compare the different models for the same sampling approach

# BPOT
```{r,echo=FALSE}

# adjust the speed_ub to be lower if the error non-finite value exists (default = 60)
log_M <- run_single_bpot(Dat.CN, model = "log", thres = c(u1, v1), xcrash = x0_1)
neglog_M <- run_single_bpot(Dat.CN, model = "neglog", thres = c(u1, v1), xcrash = x0_1) 
hr_M <- run_single_bpot(Dat.CN, model = "hr", thres = c(u1, v1), xcrash = x0_1)
ct_M <- run_single_bpot(Dat.CN, model = "ct", thres = c(u1, v1), xcrash = x0_1)
alog_M <- run_single_bpot(Dat.CN, model = "alog", thres = c(u1, v1),xcrash = x0_1)
aneglog_M <- run_single_bpot(Dat.CN, model = "aneglog", thres = c(u1, v1), xcrash = x0_1)
# bilog_M <- run_single_bpot(Dat.CN, model = "bilog", thres = c(u1, v1), xcrash = x0_1)


all_bpot_results <- list("logistic"= log_M,
                    "neglogistic"= neglog_M,
                    "hr"= hr_M,
                    "ct"= ct_M,
                    "alogistic"= alog_M,
                    "aneglogistic"= aneglog_M)
summarise_bpot(all_bpot_results)
all_bpot_densities <- lapply(all_bpot_results, function(x) x$plot_df)

plot_crash_severity(all_bpot_densities,injury_df = injury_df)

tbevd_plot(log_M$M, dat = Dat.CN)
tbevd_plot(ct_M$M, dat = Dat.CN)

```


# CBPOT
```{r,echo=FALSEecho}
gumbel_M <- run_single_cbpot(cop_dat_1, copula = gumbelCopula(),
                p2 = conseq_1, qcrash = qcrash_1, pot = pot_1,method = "ml")
clayton_M <- run_single_cbpot(cop_dat_1, copula = claytonCopula(),
                p2 = conseq_1, qcrash = qcrash_1, pot = pot_1,method = "ml")
gaussian_M <- run_single_cbpot(cop_dat_1,copula = normalCopula(dispstr = "ex"),
                p2 = conseq_1, qcrash = qcrash_1, pot = pot_1,
                method = "ml")


plot_crash_severity_single(gumbel_M$plot_df_q, injury_df)
all_cbpot_results <- list("gumbel"= gumbel_M,
                    "clayton"= clayton_M,
                    "gaussian"= gaussian_M)
summarise_cbpot(all_cbpot_results)

all_cbpot_densities <- lapply(all_cbpot_results, function(x) x$plot_df_q)
plot_crash_severity(all_cbpot_densities,injury_df = injury_df)
```

