---
title: "Comparison of estimation methods for BPOT"
output: html_notebook
---

Here we compare the different estimation methods for the same data

# logistic model
```{r,echo=FALSE}
# using censored likelihood
log_r1 <- run_single_bpot(Dat.CN, model = "log", thres = c(u1, v1),speed_ub = 55,
                          xcrash = x0_1)
log_r1$M$estimate
# using Poisson likelihood
log_r2 <- run_single_bpot(Dat.CN, model = "log", thres = c(u1, v1),speed_ub = 60,
                          xcrash = x0_1,estim = "poisson")
log_r2$M$estimate
# using marginal approach
log_r3 <- run_single_bpot(Dat.CN, model = "log", thres = c(u1, v1),
                          xcrash = x0_1,estim = "margins")
log_r3$M$estimate

# censored likelihood with marginal approach
margin_param <- log_r3$M$estimate[1:4]
log_r4 <- fbvpot(Dat.CN, model = "alog", thres = c(u1, v1),scale1=margin_param[1], scale2=margin_param[3],
                 shape1=margin_param[2], shape2=margin_param[4])
log_r4$estimate
#  poisson likelihood with marginal approach
log_r5 <- fbvpot(Dat.CN, model = "log", thres = c(u1, v1),scale1=margin_param[1], scale2=margin_param[3],
                 shape1=margin_param[2], shape2=margin_param[4],likelihood='poisson')
log_r5$estimate

logistic_result <- create_result_bpot(censored = log_r1, poisson = log_r2)
gof_bpot(logistic_result$censored$M, Dat.CN)
gof_bpot(logistic_result$poisson$M, Dat.CN)

tbevd_plot(logistic_result$censored$M, dat = Dat.CN)
tbevd_plot(logistic_result$poisson$M, dat = Dat.CN)
tbevd_plot(log_r1$M, dat = Dat.CN)

plot_crash_severity_single(log_r1$plot_df, injury_df)
plot_crash_severity_single(log_r2$plot_df, injury_df)
plot_crash_severity_single(log_r3$plot_df, injury_df)
plot_crash_severity(list(poisson = log_r2$plot_df, margins = log_r3$plot_df),
                    injury_df)

summarise_bpot(logistic_result, severity = pis0, severity_age = pis1)
```

I would like to try several things
- (checked) censored likelihood with marginal approach: got almost the same result as joint approach
- (checked) poisson likelihood with marginal approach: got different result from joint approach, but almost the same result marginal copula approach.
- (checked) difference between marginal approach and joint approach for mixture of light and heavy tail margins (data don't support it)
- Results for the pair PET, Speed_PET

Conclusion
 - The combination of Bayesian and MLE for estimating non-stationary margin and dependence parameter can be used. However the data does not allow us to see whetehr there is a difference between marginal and joint approach when the margins are mixed with light and heavy tails, as claimed in the paper.
 - the poisson likelihood is similar to the copula likelihood