---
title: "Dependence models"
output:
  html_document:
    df_print: paged
---

The notebook replicate the result section 4.1

```{r,echo=FALSE,include=FALSE}
source('../scripts/fitBPOT.R')
source('../scripts/fitCBPOT.R')
# source('../scripts/fitBPOT_joint.R')
```

# illustration of sample dependence (figure 1)
```{r,echo=FALSE}
Dat.PET_above <- Dat.PET[Dat.PET$prox > sort(Dat.PET$prox, decreasing = TRUE)[thres_order] & 
                           Dat.PET$Speed > sort(Dat.PET$Speed, decreasing = TRUE)[thres_order], ]
ggplot(data = Dat.PET,aes(x=prox,y=Speed)) +
  geom_point(size=0.5) +
  geom_point(data = Dat.PET_above, aes(x=prox,y=Speed, color='BPOT'),size=1.6) +
  geom_point(data = subset(Dat.PET,prox>quantile(Dat.PET$prox, 1 - pu_default, na.rm = TRUE)),
             aes(x=prox,y=Speed,color='CBPOT'), ,size=.9) +
  geom_vline(xintercept = sort(Dat.PET$prox, decreasing = TRUE)[thres_order], linetype="dashed", color = "red") +
  geom_hline(yintercept = sort(Dat.PET$Speed, decreasing = TRUE)[thres_order], linetype="dashed", color = "red") +
  geom_vline(xintercept = quantile(Dat.PET$prox, 1 - pu_default, na.rm = TRUE), linetype="dashed", color = "blue") +
  labs(title="negated PET", x="PET (s)", y="Speed (km/h)", color="sample") +
  scale_color_manual(values=c("BPOT"="red","CBPOT"="blue")) + 
  annotate("text", x = -5, y = 40, 
           label = paste0("BPOT correlation tau=",round(cor(Dat_above,method = "kendall")[1,2],2)), 
           color = "red") +
  annotate("text", x = -5, y = 37, 
           label = paste0("CBPOT correlation tau=",round(cor(subset(Dat,prox>v_cbpot),method = "kendall")[1,2],2)), 
           color = "blue") +
  theme_minimal()

Dat_above <- Dat[Dat$prox > u & Dat$Speed > v, ]
ggplot(data = Dat,aes(x=prox,y=Speed)) +
  geom_point(size=0.5) +
  geom_point(data = Dat_above, aes(x=prox,y=Speed, color='BPOT'),size=1.6) +
  geom_point(data = subset(Dat,prox>v_cbpot), aes(x=prox,y=Speed,color='CBPOT'), ,size=.9) +
  geom_vline(xintercept = u, linetype="dashed", color = "red") +
  geom_hline(yintercept = v, linetype="dashed", color = "red") +
  geom_vline(xintercept = v_cbpot, linetype="dashed", color = "blue") +
  labs(title="transformed PET", x="iPET", y="Speed (km/h)", color="sample") +
  scale_color_manual(values=c("BPOT"="red","CBPOT"="blue")) + 
  annotate("text", x = 0.5, y = 40,
           label = paste0("BPOT correlation tau=",round(cor(Dat_above,method = "kendall")[1,2],2)), 
           color = "red") +
  annotate("text", x = 0.5, y = 37, 
           label = paste0("CBPOT correlation tau=",round(cor(subset(Dat,prox>v_cbpot),method = "kendall")[1,2],2)), 
           color = "blue") +
  theme_minimal()
```

# BPOT (Table 2)
```{r,echo=FALSE,warning=FALSE}

# CI crash frequency
ci_sim(x0,tt1) * exposure_day * 356 #BPOT

# CI dependence parameters
c(log_M$M$estimate[5]-log_M$M$std.err * 1.96,log_M$M$estimate[5]+log_M$M$std.err * 1.96)
c(hr_M$M$estimate[5]-hr_M$M$std.err * 1.96,hr_M$M$estimate[5]+hr_M$M$std.err * 1.96)
c(neglog_M$M$estimate[5]-neglog_M$M$std.err * 1.96,neglog_M$M$estimate[5]+neglog_M$M$std.err * 1.96)
c(ct_M$M$estimate[5:6]-ct_M$M$std.err * 1.96,ct_M$M$estimate[5:6]+ct_M$M$std.err * 1.96)
c(bilog_M$M$estimate[5:6]-bilog_M$M$std.err * 1.96,bilog_M$M$estimate[5:6]+bilog_M$M$std.err * 1.96)
c(alog_M$M$estimate[5:7]-alog_M$M$std.err * 1.96,alog_M$M$estimate[5:7]+alog_M$M$std.err * 1.96)

summarise_bpot(all_bpot_results,severity_thresholds = c(20,30,40,50),
               severity = pis0,x0=x0, severity_age = pis1,age_mean = 45,expo = exposure_day* 365)
plot_crash_severity(lapply(all_bpot_results, function(x) x$plot_df),
                    filename = "crash_severity_BPOT.png")
```

## BPOT pickands dependence functoin and spectral densites

```{r,echo=FALSE}
tbevd_plot_multi(lapply(all_bpot_results, function(x) x$M),dat = Dat,filename = "BPOT_diagnostic_spectral.png")
tbevd_plot_multi(lapply(all_bpot_results, function(x) x$M),dat = Dat,type="pickands",
                 filename = "BPOT_diagnostic_dependence.png")
```

# CBPOT (Table 3)
```{r,echo=FALSE,warning=FALSE}
summarise_cbpot(all_cbpot_results,severity_thresholds = c(20,30,40,50),x0=x0,severity = pis0,
                expo = exposure_day* 365)
plot_crash_severity(lapply(all_cbpot_results, function(x) x$plot_df_q),
                    filename = "crash_severity_CBPOT.png")
```


