---
title: "Supplement material 2: Comparison of estimation methods for BPOT"
output:
  html_document:
    df_print: paged
---

```{r,include=FALSE}
source('../scripts/preprocessing.R')
source("../scripts/global_vars.R")
```

Here we compare the different estimation methods for the same data

# estim model
```{r,echo=FALSE,warning=FALSE}
# using joint censored likelihood
estim_r1 <- run_single_bpot(Dat, model = "log", thres = c(u, v),xcrash = x0)
estim_r1$M$estimate
# using joint Poisson likelihood
estim_r2 <- run_single_bpot(Dat, model = "log", thres = c(u, v),xcrash = x0,likelihood = "poisson")
estim_r2$M$estimate
# using marginal censored likelihood
estim_r3 <- run_single_bpot(Dat, model = "log", thres = c(u, v),
                          xcrash = x0,estim = "margins")
estim_r3$M$estimate

#  poisson likelihood with marginal approach
estim_r4 <- run_single_bpot(Dat, model = "log", thres = c(u, v),
                          xcrash = x0,estim = "margins",likelihood = "poisson")
estim_r4$M$estimate


estim_result <- list(censored_J=estim_r1,poisson_J=estim_r2,censored_M = estim_r3, poisson_M = estim_r4)

plot_crash_severity(lapply(estim_result, function(x) x$plot_df))
```