---
title: 'Sensitivity of crash severity '
output:
  html_document:
    df_print: paged
---

```{r,echo=FALSE,include=FALSE}
source('../scripts/fitModels.R')
```

# Sensitivity of crash severity density
```{r,echo=FALSE,warning=FALSE}
# one parameter model
sen_log_M <- bpot_theoretical_density(c(0.6,0.7,0.8,0.9,0.99), log_M)
sen_hr_M <- bpot_theoretical_density(c(0.2, 0.5, 0.8,1.2,1.6), hr_M)
sen_neglog_M <- bpot_theoretical_density(c(0.05, 0.2, 0.45,0.6,0.85), neglog_M)

plot_theoretical_density(sen_log_M,include_origin = FALSE,
                         title = "theoretical density of crash severity: log BEVD")
plot_theoretical_density(sen_hr_M,include_origin = FALSE,
                         title = "theoretical density of crash severity: hr BEVD")
plot_theoretical_density(sen_neglog_M,include_origin = FALSE,
                         title = "theoretical density of crash severity: neglog BEVD")
```

```{r,echo=FALSE,warning=FALSE}
# two parameters 
sen_ct_M_alpha <- bpot_theoretical_density(list(c(0.5,1), c(0.5,2),c(0.5,3),c(0.5,4),c(0.5,5)), ct_M)
sen_ct_M_beta <- bpot_theoretical_density(list(c(1,0.5), c(2,0.5),c(3,0.5),c(4,0.5),c(5,0.5)), ct_M)
sen_bilog_M_alpha <- bpot_theoretical_density(list(c(0.5,0.2), c(0.5,0.4),c(0.5,0.6),c(0.5,0.8),c(0.5,0.99)), bilog_M)
sen_bilog_M_beta <- bpot_theoretical_density(list(c(0.2,0.5), c(0.4,0.5),c(0.6,0.5),c(0.8,0.5),c(0.99,0.5)), bilog_M)

plot_theoretical_density(sen_ct_M_alpha,include_origin = FALSE,
                         title = "theoretical density of crash severity: ct BEVD (varying alpha)")
plot_theoretical_density(sen_ct_M_beta,include_origin = FALSE,
                         title = "theoretical density of crash severity: ct BEVD (varying beta)")
plot_theoretical_density(sen_bilog_M_alpha,include_origin = FALSE,
                         title = "theoretical density of crash severity: bilog BEVD (varying alpha)")
plot_theoretical_density(sen_bilog_M_beta,include_origin = FALSE,
                         title = "theoretical density of crash severity: bilog BEVD (varying beta)")

```

```{r,echo=FALSE,warning=FALSE}
# CBPOT approach
sen_gumbel_M <- cbpot_theoretical_density(c(1, 1.2, 1.4,1.6), "gumbel",gumbel_M)
sen_clayton_M <- cbpot_theoretical_density(c(-0.6,-0.3, -0.05 , 0.1,3,5), "clayton",clayton_M)
sen_gaussian_M <- cbpot_theoretical_density(c(-0.7,-0.4,-0.1, 0.1, 0.4,0.7), "normal",gaussian_M)

plot_theoretical_density(sen_gumbel_M,include_origin = FALSE,
                         title = "theoretical density of crash severity: Gumbel copula")
plot_theoretical_density(sen_clayton_M,include_origin = FALSE,
                         title = "theoretical density of crash severity: Clayton copula")
plot_theoretical_density(sen_gaussian_M,include_origin = FALSE,
                         title = "theoretical density of crash severity: Gaussian copula")
```

# sensitivity of injury probability
```{r,echo=FALSE}
age_mean_list <- seq(20, 60, by = 1)

injury_sen_log_M <- bpot_theoretical_injury(c(0.6,0.7,0.8,0.9,0.99), log_M, age_mean_list,
                                          filename = "injury_sensitivity_log.csv")
injury_sen_hr_M <- bpot_theoretical_injury(c(0.2, 0.5, 0.8,1.2,1.6), hr_M, age_mean_list,
                                          filename = "injury_sensitivity_hr.csv")
injury_sen_neglog_M <- bpot_theoretical_injury(c(0.05, 0.2, 0.45,0.6,0.85), neglog_M, age_mean_list,
                                          filename = "injury_sensitivity_neglog.csv")

injury_sen_gumbel_M <- cbpot_theoretical_injury(c(1, 1.2, 1.4,1.6), "gumbel",
                                       gumbel_M, age_mean_list,conseq,filename = "injury_sensitivity_gumbel.csv")
injury_sen_clayton_M <- cbpot_theoretical_injury(c(-0.6,-0.3, -0.05,0.1,1,2.5), "clayton",
                                       clayton_M, age_mean_list,conseq,filename = "injury_sensitivity_clayton.csv")
injury_sen_gaussian_M <- cbpot_theoretical_injury(c(-0.7,-0.4,-0.1, 0.1, 0.4,0.7), "normal",
                                       gaussian_M, age_mean_list,conseq,filename = "injury_sensitivity_gaussian.csv")

plot_theoretical_injury(injury_sen_log_M)
plot_theoretical_injury(injury_sen_hr_M)
plot_theoretical_injury(injury_sen_neglog_M)
plot_theoretical_injury(injury_sen_gumbel_M)
plot_theoretical_injury(injury_sen_clayton_M)
plot_theoretical_injury(injury_sen_gaussian_M)

```

